MediVol/MediVol/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from MediVol.views import *

dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MediVol.views.home', name='home'),
    # url(r'^MediVol/', include('MediVol.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    #Routing for Login
    url(r'^$', custom_login),
    url(r'^login/$', custom_login),

    #Routing for Logout
    url(r'^logout/$', 'administration.views.logout'),

    #Routing for Administration Main Page
    url(r'^administration/', include('administration.urls')),

    #Routing for Inventory
    url(r'^inventory/', include('inventory.urls')),

    #Routing for Orders
    url(r'^orders/', include('orders.urls')),

    #Routing for Catalog
    url(r'^catalog/', include('catalog.urls')),

    #Routing for Labels 
    url(r'^label/', include('label.urls')),
)

MediVol/inventory/urls.py
from django.conf.urls import patterns, url

from inventory import views

urlpatterns = patterns('',
    url(r'^create/$', views.create, name='create'),
    url(r'^create/(?P<order_id>\w+)/$', views.create, name='create'),
    url(r'^edit/(?P<box_id>\w+)/$', views.edit, name='edit'),
    url(r'^view_box_info/(?P<boxid>\w+)/$', views.box_info, name='box_info'),
    url(r'^view_box_info/barcode/(?P<barcodeid>\w+)/$', views.barcode_box_info, name='box_info'),
    url(r'^box_transfer/$', views.box_transfer, name='box_transfer'),
    url(r'^$',views.inventory_view,name='inventory_view')
)

MediVol/label/urls.py
from django.conf.urls import patterns, url

from label import views

urlpatterns = patterns('', 
  url(r'^create/(?P<box_barcode>\w+)/$', views.create_label, name='create'),
)

MediVol/inventory/models.py
import pytz
from django.db import models
from catalog.models import Item, Category
from import_export.to_csv import to_csv_from_array, to_array_from_csv
from datetime import datetime, date
import random
from MediVol import id_generator

NAME_LENGTH = 80
ABBREV_LENGTH = 4
ADDRESS_LENGTH = 200
BOX_ID_LENGTH = 6
BARCODE_LENGTH = 8

class Warehouse(models.Model):
    name = models.CharField(max_length=NAME_LENGTH)
    abbreviation = models.CharField(max_length=ABBREV_LENGTH, unique=True)
    address = models.CharField(max_length=ADDRESS_LENGTH)
    is_default = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

class Box(models.Model):
    SMALL = 'S'
    LARGE = 'L'
    UNKNOWN = 'U'
    SIZE_CHOICES = (
        (SMALL, 'Small'),
        (LARGE, 'Large'),
        (UNKNOWN, 'Unknown'),
    )
    #set on save
    box_id = models.CharField(max_length=BOX_ID_LENGTH, null=True, unique=True)
    barcode = models.CharField(max_length=BARCODE_LENGTH, unique=True)

    #set on box_contents save
    box_category = models.ForeignKey(Category, null=True)

    #set on creation
    box_size = models.CharField(max_length=1, choices=SIZE_CHOICES, default=UNKNOWN, null=True)
    weight = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    initials = models.CharField(max_length=5, default="")
    note = models.CharField(max_length=300, null=True)
    entered_date = models.DateTimeField('date the box was entered', null=True)
    warehouse = models.ForeignKey(Warehouse, null=True)

    #working with old boxes
    old_box_flag = models.BooleanField(default=False)
    old_expiration = models.DateTimeField('expiration date', null=True)
    old_contents = models.CharField(max_length=300, null=True)
    #TODO: Ask Amy what this could mean
    box_date = models.DateTimeField('Box date', null=True)
    #TODO what does this mean?
    audit = models.IntegerField(default=1, null=True)

    @classmethod
    def get_box(self, box_id_to_get):
        box = None

        try:
            box = Box.objects.get(box_id=box_id_to_get)
        except Box.DoesNotExist:
            boxes = Box.objects.raw(
                '''SELECT * FROM inventory_box
                INNER JOIN catalog_category ON inventory_box.box_category_id = catalog_category.id
                WHERE CONCAT(catalog_category.letter, inventory_box.box_id) = %s''',
                [box_id_to_get]
            )

            for box_found in boxes:
                box = Box.objects.get(box_id=box_found.box_id)
                break

        return box

    @classmethod
    def create_from_csv(cls, csv):
        filtered_values = to_array_from_csv(csv)
        box = Box(box_id=filtered_values[0],
                  barcode=filtered_values[1],

                  box_category=Category.objects.get(letter=filtered_values[2]),

                  box_size=filtered_values[3],
                  weight=filtered_values[4],
                  initials=filtered_values[5],
                  note=filtered_values[6],
                  entered_date=filtered_values[7],
                  warehouse=Warehouse.objects.get(abbreviation=filtered_values[8]),

                  old_box_flag=filtered_values[10],
                  old_expiration=filtered_values[11],
                  old_contents=filtered_values[12],
                  box_date=filtered_values[13],
                  audit=filtered_values[14])
        box.save()
        return box

    def is_locked_out(self):
        orderbox_list = self.orderbox_set.all()

        for orderbox in orderbox_list:
            if orderbox.order_for.locks_out_boxes():
                return True

        return False

    def get_url(self):
        return '<a href="/inventory/view_box_info/' + self.get_id() +'" target="_blank">' + self.get_id() + '</a>'

    def get_size_word(self):
        return self.SIZE_CHOICES[self.box_size]

    def __unicode__(self):
        """
        Returns a printable, human readable, string to represent the Box
        """
        return self.get_id()

    def save(self, *args, **kwargs):
        """
        During that save process we will assign a barcode to the Box, if it does not already have one (ie a new box)
        To make a barcode this method will generate an 8 digit number (with leading zeros), then validate that the
        generated number is not already in use.
        """
        #TODO remove try catch as something is figured out with id uniqueness
        try:
            if self.barcode == None or self.barcode== '':
                while True: #guess until we have a unique barcode
                    self.barcode = "%0.8d" % random.randint(0,99999999) #make a guess
                    if not Box.objects.filter(barcode=self.barcode).exists():
                        break #if the guess was unique stop
        except Exception as e:
            #I think if this gets called, it will crash the webpage for trying to execute print
            print ('%s (%s)' % ('The Box did not save correctly', type(e)))

        if self.box_id is None:
            self.box_id = "%0.6d" % len(Box.objects.all())
            while True:
                if not Box.objects.filter(box_id=self.box_id).exists():
                    break
                self.box_id = "%0.6d" % (int(self.box_id) + 1)

        super(Box, self).save(*args, **kwargs)

    def to_csv(self):
        """
        Returns a string containing all the CSV information of the Box.  Used in creating database backups
        """
        values = [self.box_id,
                  str(self.barcode),

                  self.box_category.letter,

                  self.box_size,
                  str(self.weight),
                  self.initials,
                  self.note,
                  str(self.entered_date),
                  self.warehouse.abbreviation,

                  self.old_box_flag,
                  str(self.old_expiration),
                  self.old_contents,
                  str(self.box_date),
                  str(self.audit)]
        return to_csv_from_array(values)

    def get_id(self):
        if self.old_box_flag:
            return self.box_id
        return self.box_category.letter + self.box_id

    def get_printable_id(self):
        if self.old_box_flag:
            return self.box_id
        return self.box_category.letter + '-' + self.box_id

    def get_expiration(self):
        """
        Finds the oldest date amoung the contents of a Box, and return it.
        For example if an item is expireing on 01-01-2014 and another is expireing on 01-01-2012, 01-01-2012 will be
        returned
        """
        if self.old_expiration is not None:
            return self.old_expiration
        NOT_EXPIRING_IN_THIS_MILLENIUM = datetime(3013,1,1,0,0,0,0,pytz.UTC)
        expiration = NOT_EXPIRING_IN_THIS_MILLENIUM
        for item in self.contents_set.all():
            #if the item has an expiration that is older than the oldest replace it
            if item.expiration is not None and item.expiration < expiration:
                expiration = item.expiration
        if expiration is NOT_EXPIRING_IN_THIS_MILLENIUM:
            return None
        return expiration

    def get_expiration_display(self):
        expiration = self.get_expiration()

        if expiration is None:
            return 'Never'
        else:
            formatted_expiration = expiration.strftime('%B, %Y')

            if formatted_expiration == 'January, 1970':
                return 'Unknown'
            else:
                return formatted_expiration

    def get_printable_expiration(self):
        expiration = self.get_expiration()

        if expiration is None:
            return 'Never'
        else:
            formatted_expiration = expiration.strftime('%m/%Y')

            if formatted_expiration == 'January, 1970':
                return '??/????'
            else:
                return formatted_expiration

    def get_search_results_string(self):
        if self.old_box_flag:
            return 'Box ' + self.get_id() + ' (Old Box. Contents: "' + self.old_contents + '")'
        else:
            return 'Box ' + self.get_id()

    def get_contents_string(self, with_links=False):
        if self.old_contents is None:
            contents_strings = []
            contents = Contents.objects.filter(box_within=self)

            for content in contents:
                if with_links:
                    if content.quantity > 0:
                        contents_strings.append(
                            '<a href="/catalog/item_info/%s" target="_blank">%s</a> x %s' % \
                            (content.item.id, content.item.name, str(content.quantity))
                        )
                    else:
                        contents_strings.append(
                            '<a href="/catalog/item_info/%s" target="_blank">%s</a>' % \
                            (content.item.id, content.item.name)
                        )
                else:
                    if content.quantity > 0:
                        contents_strings.append(content.item.name + ' x ' + str(content.quantity))
                    else:
                        contents_strings.append(content.item.name)

            return ', '.join(contents_strings)

        return self.old_contents

    def get_contents_string_with_links(self):
        return self.get_contents_string(True)
    
    def get_most_populous_box_name(self):
        most_populous = ''
        highest_quantity = 0;
        contents = Contents.objects.filter(box_within=self)
        for content in contents:
            if content.quantity >= highest_quantity or most_populous == '':
                highest_quantity = content.quantity
                most_populous = content.item.box_name.name
        return most_populous

class Contents(models.Model):
    box_within = models.ForeignKey(Box)
    item = models.ForeignKey(Item)
    quantity = models.IntegerField(default=0)

MediVol/inventory/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from administration.UserTests import UserTests

from catalog.models import Category
from inventory.models import Box, Contents, Warehouse
from orders.models import Order, OrderBox

@login_required(login_url='/login/')
@user_passes_test(UserTests.user_can_create_box, login_url='/administration/forbidden')
def create(request, order_id=0):
    categories = Category.objects.all()
    categoryStrings = []

    for category in categories:
        categoryStrings.append(category.name)

    order = False

    if order_id != 0:
        order = Order.objects.get(id=order_id)

    context = {
        'categories': sorted(categoryStrings),
        'order_id': order_id,
        'order': order,
        'warehouses': Warehouse.objects.all(),
        'box': None
    }

    return render(request, 'inventory/create.html', context)

@login_required(login_url='/login/')
@user_passes_test(UserTests.user_can_create_box, login_url='/administration/forbidden')
def edit(request, box_id):
    box = Box.get_box(box_id)

    if box is None:
        return render(request, 'inventory/box_not_found.html')

    categories = Category.objects.all()
    categoryStrings = []

    for category in categories:
        categoryStrings.append(category.name)

    context = {
        'categories': sorted(categoryStrings),
        'order_id': 0,
        'warehouses': Warehouse.objects.all(),
        'box': box
    }

    return render(request, 'inventory/create.html', context)

@login_required(login_url='/login')
@user_passes_test(UserTests.user_can_see_box_info, login_url='/administration/forbidden')
def box_info(request, boxid):
    #Try and get box info from the box id if exists return
    box = Box.get_box(boxid)

    if box is None:
        return render(request, 'inventory/box_not_found.html')

    box_contents = []

    if box.old_contents is None:
        box_contents = Contents.objects.filter(box_within=box)
    else:
        box_contents = box.old_contents

    # Search if box is related to orders.
    order_boxes = OrderBox.objects.filter(box=box)

    if len(order_boxes) == 0:
        orders = None
    else:
        order_links = []

        for order_box in order_boxes:
            order_links.append('<a href="/orders/review/' + order_box.order_for.order_number +
                '" target="_blank">' + order_box.order_for.order_number + '</a>')

        orders = ', '.join(order_links)

    context = {
        'box': box,
        'box_contents': box_contents,
        'orders': orders,
        'warehouses': Warehouse.objects.all()
    }

    return render(request, 'inventory/box_info.html', context)

@login_required(login_url='/login/')
@user_passes_test(UserTests.user_can_see_box_info, login_url='/administration/forbidden')
def barcode_box_info(request, barcodeid):
    try:
        #Try and get the box info from the box id if exists return
        box = Box.objects.get(barcode=barcodeid)
        box_contents = []

        if box.old_contents is None:
            box_contentss = Contents.objects.filter(box_within=box)
        else:
            box_contents = box.old_contents

        # Search if box is related to orders.
        try:
            order_box = OrderBox.objects.get(box=box)
            order_number = Order.objects.get(order).order_number
        except OrderBox.DoesNotExist:
            order_number = None

        context = { 'box': box, 'box_contents': box_contents, 'order_number': order_number }

        return render(request, 'inventory/box_info.html', context)
    except Box.DoesNotExist:
        #If box does not exist in databse redirect to box not found page
        return render_to_response('inventory/box_not_found.html')

@login_required(login_url='/login/')
@user_passes_test(UserTests.user_can_see_inventory, login_url='/administration/forbidden')
def inventory_view(request):
    categories = Category.objects.all()
    categoryStrings = []

    for category in categories:
        categoryStrings.append(category.name)

    context = { 'categories': sorted(categoryStrings) }

    return render(request, 'inventory/inventory.html', context)

@login_required(login_url='/login/')
@user_passes_test(UserTests.user_can_transfer_boxes, login_url='/administration/forbidden')
def box_transfer(request):
    context = { 'warehouses': Warehouse.objects.all() }

    return render(request, 'inventory/box_transfer.html', context)

MediVol/inventory/templates/inventory/box_info.html
{% extends "base.html" %}

{% block title %}
    <title>InterVol | Box {{ box.get_id }}</title>
{% endblock %}

{% block styles %}
    <link rel='stylesheet' href='{{ STATIC_URL }}inventory/css/box_info.css' />
{% endblock %}

{% block body %}
    <h2>Box {{ box.get_id }} </h2>
    {% if orders != None %}
        <h3 id='createdDate'>
            In <a href='/orders/review/{{ order.order_number }}'>{{ orders|safe }}</a>
        </h3>
    {% endif %}

    {% if box.entered_date != None %}
        <h3 id='createdDate'>Created on {{ box.entered_date }}</h3>
    {% endif %}

    <div id='boxInfoWrapper'>
        <div class='attributeWrapper'>
            <h3 class='attributeLabel'>Category</h3>
            <p class='attributeValue'>{{ box.box_category }}</p>
            <div class='clear'></div>
        </div>

        <div class='attributeWrapper'>
            <h3 class='attributeLabel'>Size</h3>
            <p class='attributeValue'>{{ box.get_box_size_display }}</p>
            <div class='clear'></div>
        </div>

        <div class='attributeWrapper'>
            <h3 class='attributeLabel'>Weight</h3>

            {% if box.weight != None %}
                <p class='attributeValue'>{{ box.weight|floatformat:'1' }} lbs</p>
            {% else %}
                <p class='attributeValue'>Unknown</p>
            {% endif %}
            <div class='clear'></div>
        </div>
        <div class='attributeWrapper'>
            <h3 class='attributeLabel'>Entered By</h3>
            <p class='attributeValue'>
                {% if box.initials == '' %}
                    Unknown
                {% else %}
                    {{ box.initials }}
                {% endif %}
            </p>
            <div class='clear'></div>
        </div>

        <div class='attributeWrapper'>
            <h3 class='attributeLabel'>Expires</h3>
            <p class='attributeValue'>{{ box.get_expiration_display }}</p>
        </div>

        <div class='attributeWrapper'>
            <h3 class='attributeLabel'>Warehouse</h3>

            <p class='attributeValue'>
                <select id='warehouse'>
                    {% if box.warehouse == None %}
                        <option id='unknownOption' value='unknown'>Unknown</p>
                    {% endif %}

                    {% for warehouse in warehouses %}
                        {% if warehouse == box.warehouse %}
                            <option value='{{ warehouse.abbreviation }}' selected='selected'>{{ warehouse }}</option>
                        {% else %}
                            <option value='{{ warehouse.abbreviation }}'>{{ warehouse }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </p>
        </div>

        {% if box.note != None %}
            <div class='attributeWrapper fullWidth'>
                <h3 class='attributeLabel'>Note</h3>
                <p class='attributeValue'>{{ box.note }}</p>
            </div>
        {% endif %}

        <div class='attributeWrapper fullWidth'>
            <h3 class='attributeLabel'>Contents</h3>
            {% if user.is_authenticated and user.groups.all.0.name == 'Admin' %}
                <p class='attributeValue'>{{ box.get_contents_string_with_links|safe }}</p>
            {% else %}
                <p class='attributeValue'>{{ box.get_contents_string }}</p>
            {% endif %}

            {% if box.shipped_to != None and box.shipped_to != '' %}
                <h3 class='attributeLabel'>Shipped To</h3>
                <p class='attributeValue'>{{ box.shipped_to }}</p>
            {% endif %}
        </div>

        <div class='clear'></div>
    </div>

    <div id='boxInfoButtons'>
        <div id='buttonsLeft'>
            <a href='/inventory/'><button class='button'>&larr; Back to Inventory</button></a>
        </div>

        <div id='buttonsRight'>
            <a href='/inventory/edit/{{ box.get_id }}'><button id="edit_box"  class='button'>Edit Box</button></a>
            <button id="print_label" onclick="print_label('{{box.box_id }}')" class='button'>Print Label</button>
            <button id="delete_box" onclick="deleteBox('{{box.box_id }}')" class='button'>Delete Box</button>
        </div>

        <div class='clear'></div>
    </div>
{% endblock %}

{% block javascript %}
    <script type='text/javascript'>
        var boxId = '{{ box.get_id }}';
    </script>

    <script type='text/javascript' src='{{ STATIC_URL }}inventory/js/box_info.js'></script>
{% endblock %}

MediVol/inventory/templates/inventory/box_not_found.html
{% extends "base.html" %}

{% block title %}
    <title>InterVol | Box Not Found</title>
{% endblock %}

{% block body %}
    <h2>Box Not Found</h2>
{% endblock %}

MediVol/inventory/templates/inventory/create.html
{% extends "base.html" %}

{% block title %}
    {% if box == None %}
        <title>InterVol | Create Box</title>
    {% else %}
        <title>InterVol | Edit Box {{ box.get_id }}</title>
    {% endif %}
{% endblock %}

{% block styles %}<link rel='stylesheet' href='{{ STATIC_URL }}inventory/css/styles.css' />{% endblock %}

{% block body %}

{% if box == None%}
    <h2>Create Box - Step <span id='stepNumber'>1</span>/2</h2>
{% else %}
    <h2>Edit Box {{ box.get_id }} - Step <span id='stepNumber'>1</span>/2</h2>
{% endif %}

{% if order_id != 0 %}
    <h3 class='forOrder'>For {{ order.order_number }}</h2>
{% endif %}

<form id='create_box_form' action='' method='post'>
{% csrf_token %}

<input type='hidden' id='orderId' value='{{ order_id }}' />

<div id='stepOne'>
    <div id='stepOneFields'>
        <p id='emptyBoxMessage' class='requiredText requiredMessage'>Boxes must have at least one item.</p>

        <input type='text' id='itemSearch' class='textField'
            placeholder='Search for a category, box name, or item...' />

        <div id='or'>
            -- or --
        </div>

        <div id='createBoxLists'>
            <div class='createBoxListWrapper'>
                <h3>Categories</h3>

                <select id='categories' size=10>
                    {% for category in categories %}
                        <option>{{ category }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class='createBoxListWrapper'>
                <h3>Box Names</h3>

                <select id='box_names' size=10></select>
            </div>

            <div class='createBoxListWrapper'>
                <h3>Items</h3>

                <select id='items' size=10></select>
            </div>

            <div class='clear'></div>
        </div>

        <div id='itemSelectedMessage' class='noItemSelected'>
            Please select an item.
        </div>

        <div id='itemInfoWrapper'>
            <div class='infoFieldWrapper'>
                <p>How many?</p>
                <input type='number' class='textField' min=1 id='count' />
                <p class='smallNote'>* Leave blank for not counted.</p>
            </div>

            <div class='infoFieldWrapper'>
                <p>Expiration date?</p>
                <input type='month' class='textField' id='expiration' />
                <p class='smallNote'>* Leave as is for never.</p>
            </div>
            <div class='infoFieldWrapper'>
                <button id='add_item' class='button'>Add Item</button>
            </div>
        </div>

        <p id='boxCategoryMessage' class='requiredText requiredMessage'>
            Boxes can only contain one category of items
        </p>
    </div>

    <div id='tableWrapper'>
        <table id='items_added'>
            <tr id='table_header'>
                <td>Category</td>
                <td>Box Name</td>
                <td>Item</td>
                <td>Expiration</td>
                <td>Count</td>
            </tr>

            {% if box == None %}
                <tr id='placeholder_row'>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>&nbsp;</td>
                </tr>
            {% else %}
                {% for content in box.contents_set.all %}
                    <tr>
                        <td>{{ content.item.box_name.category.name }}</td>
                        <td>{{ content.item.box_name.name }}</td>
                        <td>{{ content.item.name }}</td>
                        <td>{{ content.get_expiration_display }}</td>
                        <td>{{ content.get_quantity_display }}</td>
                        <td><a class="remove_item" href="javascript:void(0)">Remove</a></td>
                    </tr>
                {% endfor %}
            {% endif %}
        </table>
    </div>

    <input type='button' id='next' class='button' value='Next Step &rarr;' />
</div>

<div id='stepTwo'>
    <p id='requiredFieldsMessage' class='requiredText requiredMessage'>Please fill out the required fields.</p>

    <div id='stepTwoFields'>
        <div class='stepTwoField'>
            <div class='label'>
                &nbsp;
            </div>

            <div class='stepTwoFieldWrapper requiredText'>
                *required
            </div>

            <div class='clear'></div>
        </div>

        <div class='stepTwoField'>
            <div class='label'>
                Initials<span class='requiredText'>*</span>
            </div>

            <div class='stepTwoFieldWrapper'>
                {% if box != None %}
                    <input type='text' placeholder='(required)' value='{{ box.initials }}'
                        id='initials' name='initials' class='textField' />
                {% else %}
                    <input type='text' placeholder='(required)' id='initials' name='initials' class='textField' />
                {% endif %}
            </div>

            <div class='clear'></div>
        </div>

        <div class='stepTwoField'>
            <div class='label'>
                Weight<span class='requiredText'>*</span>
            </div>

            <div class='stepTwoFieldWrapper'>
                {% if box != None %}
                    <input name='weight' id='weight' type='number' value='{{ box.weight }}' class='textField' />
                {% else %}
                    <input name='weight' id='weight' type='number' class='textField' />
                {% endif %}
            </div>

            <div class='clear'></div>
        </div>

        <div class='stepTwoField'>
            <div class='label'>
                Size<span class='requiredText'>*</span>
            </div>

            <div class='stepTwoFieldWrapper'>
                {% if box != None and box.box_size == 'S' %}
                    <label for='small'><input type='radio' checked='checked' name='size'
                        id='small' value='Small'> Small</label><br />
                {% else %}
                    <label for='small'><input type='radio' name='size' id='small' value='Small'> Small</label><br />
                {% endif %}

                {% if box != None and box.box_size == 'L' %}
                    <label for='large'><input type='radio' name='size' id='large'
                        checked='checked' value='Large' class='largeRadio'> Large</label>
                {% else %}
                    <label for='large'><input type='radio' name='size' id='large'
                        value='Large' class='largeRadio'> Large</label>
                {% endif %}
            </div>

            <div class='clear'></div>
        </div>

        <div class='stepTwoField'>
            <div class='label'>
                Warehouse location<span class='requiredText'>*</span>
            </div>

            <div class='stepTwoFieldWrapper'>
                <select id='warehouse_options'>
                    {% for warehouse in warehouses %}
                        {% if box == None %}
                            {% if warehouse.is_default %}
                                <option selected='selected' value='{{ warehouse.abbreviation }}'>{{ warehouse.name }}</option>
                            {% else %}
                                <option value='{{ warehouse.abbreviation }}'>{{ warehouse.name }}</option>
                            {% endif %}
                        {% else %}
                            {% if warehouse == box.warehouse %}
                                <option selected='selected' value='{{ warehouse.abbreviation }}'>{{ warehouse.name }}</option>
                            {% else %}
                                <option value='{{ warehouse.abbreviation }}'>{{ warehouse.name }}</option>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </select>
            </div>

            <div class='clear'></div>
        </div>

        {% if user.is_authenticated and user.groups.all.0.name == 'Admin' %}
            <div class='stepTwoField'>
                <div class='label'>
                    Category
                </div>

                <div class='stepTwoFieldWrapper'>
                    {% if box == None %}
                        <select id='customCategory' original=''></select>
                    {% else %}
                        <select id='customCategory' original='{{ box.box_category.name }}'></select>
                    {% endif %}
                </div>

                <div class='clear'></div>
            </div>

            <div class='stepTwoField'>
                <div class='label'>
                    Note
                </div>

                <div class='stepTwoFieldWrapper'>
                    {% if box == None %}
                        <textarea id='note' name='note' class='textField'></textarea>
                    {% elif box != None and box.note != None %}
                        <textarea id='note' name='note' class='textField'>{{ box.note }}</textarea>
                    {% elif box != None and box.note == None %}
                        <textarea id='note' name='note' class='textField'></textarea>
                    {% endif %}
                </div>

                <div class='clear'></div>
            </div>
        {% endif %}
    </div>

    <input type='button' id='back' class='button' value='&larr; Back' />

    {% if box == None %}
        <input type='submit' id='submit' class='button' value='Create Box' />
    {% else %}
        <input type='submit' id='submit' class='button' value='Save Box' />
    {% endif %}

    <div class='clear'></div>
</div>

</form>

{% endblock %}

{% block javascript %}
    <script type='text/javascript'>
        var groupName = '{{ user.groups.all.0.name }}';

        {% if box == None %}
            var boxId = 0;
        {% else %}
            var boxId = '{{ box.get_id }}';
        {% endif %}
    </script>

    <script type='text/javascript' src='{{ STATIC_URL }}inventory/js/main.js'></script>
{% endblock %}