MediVol/MediVol/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from MediVol.views import *

dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MediVol.views.home', name='home'),
    # url(r'^MediVol/', include('MediVol.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    #Routing for Login
    url(r'^$', custom_login),
    url(r'^login/$', custom_login),

    #Routing for Logout
    url(r'^logout/$', 'administration.views.logout'),

    #Routing for Administration Main Page
    url(r'^administration/', include('administration.urls')),

    #Routing for Inventory
    url(r'^inventory/', include('inventory.urls')),

    #Routing for Orders
    url(r'^orders/', include('orders.urls')),

    #Routing for Catalog
    url(r'^catalog/', include('catalog.urls')),

    #Routing for Labels 
    url(r'^label/', include('label.urls')),
)

MediVol/label/urls.py
from django.conf.urls import patterns, url

from label import views

urlpatterns = patterns('', 
  url(r'^create/(?P<box_barcode>\w+)/$', views.create_label, name='create'),
)

MediVol/orders/urls.py
from django.conf.urls import patterns, url
from orders.views import *

urlpatterns = patterns ('',
    #Orders Main Page
    url(r'^$', orders_home),
    url(r'^create/$', create_order),
    url(r'^create/(?P<order_id>\w+)/$', create_order),
    url(r'^create/(?P<order_id>\w+)/(?P<step_num>\d{1})/$', create_order),
    url(r'^create/(?P<order_id>\w+)/(?P<step_num>\d{1})/(?P<box_to_add>\w+)/$', create_order),
    url(r'^review/(?P<orderid>[\w\s]+)/$', order_review, name='review_order')
)

MediVol/orders/models.py
from django.db import models
import uuid
from inventory.models import Box
from import_export.to_csv import to_csv_from_array, to_array_from_csv
from MediVol import id_generator

ORDER_NUMBER_LENGTH = 200

class Customer(models.Model):
    contact_id = models.CharField(max_length=40, unique=True)
    contact_name = models.CharField(max_length=80, unique=False)
    contact_email = models.CharField(max_length=80)
    business_name = models.CharField(max_length=80)
    business_address = models.CharField(max_length=200, null=True)

    def __unicode__(self):
        return "Contact info for: " + self.contact_name + ' at ' + self.business_name

    def to_csv(self):
        values = [self.contact_id,
                  self.contact_name,
                  self.contact_email,
                  self.business_name,
                  self.business_address,
                  self.shipping_address]
        return to_csv_from_array(values)

    @classmethod
    def create_from_csv(cls, csv):
        filtered_values = to_array_from_csv(csv)
        customer = Customer(contact_id=filtered_values[0],
                            contact_name=filtered_values[1],
                            contact_email=filtered_values[2],
                            business_name=filtered_values[3],
                            business_address=filtered_values[4],
                            shipping_address=filtered_values[5])
        customer.save()
        return customer

    def save(self, *args, **kwargs):
        if self.contact_id is None:
            self.contact_id=str(uuid.uuid4())
        elif self.contact_id == '':
            self.contact_id=str(uuid.uuid4())
        super(Customer, self).save(*args, **kwargs)

    def get_search_results_string(self):
        return self.contact_name + ' (' + self.business_name + ')'

    class Meta:
        unique_together=('contact_name', 'business_name')

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer)
    address = models.CharField(max_length=200, unique=True)

    def __unicode__(self):
        return address

class Order(models.Model):
    CREATED = 'C'
    UNPAID = 'U'
    PAID = 'P'
    SHIPPED = 'S'
    PAID_DEPOSIT = 'D'
    CANCELLED = 'F'
    ORDER_STATUS = (
        (CREATED, 'Created'),
        (UNPAID, 'Unpaid For'),
        (PAID_DEPOSIT, 'Deposit Paid'),
        (PAID, 'Paid For'),
        (SHIPPED, 'Shipped Out'),
        (CANCELLED, 'Cancelled'),
    )
    order_number = models.CharField(unique=True, max_length=ORDER_NUMBER_LENGTH)
    reserved_for = models.ForeignKey(Customer, null=True)
    paid_for = models.BooleanField(default=False)
    shipped = models.BooleanField(default=False)
    ship_to = models.ForeignKey(ShippingAddress, null=True)
    creation_date = models.DateTimeField('Date the order was made')
    order_status = models.CharField(max_length=1, choices=ORDER_STATUS, default=CREATED)
    price = models.FloatField(null=True)

    def save(self, *args, **kwargs):
        super(Order, self).save(*args, **kwargs)

        self.lock_out_boxes()

    def __unicode__(self):
        return "Order " + str(self.order_number)

    def locks_out_boxes(self):
        return self.order_status == self.PAID or self.order_status == self.SHIPPED

    def lock_out_boxes(self):
        if not self.locks_out_boxes():
            return

        order_boxes = OrderBox.objects.filter(order_for=self)

        for order_box in order_boxes:
            other_order_boxes = order_box.box.orderbox_set.exclude(order_for=self)

            for other_order_box in other_order_boxes:
                try:
                    notification = LockedBoxNotification.objects.get(removed_from_order=other_order_box.order_for,
                        box=other_order_box.box)
                except LockedBoxNotification.DoesNotExist:
                    notification = LockedBoxNotification(removed_from_order=other_order_box.order_for,
                        box=other_order_box.box)
                    notification.save()

                other_order_box.delete()

    def to_csv(self):

        if self.reserved_for is not None:
            reservation = self.reserved_for.contact_id
        else:
            reservation = None

        values = [self.order_number,
                  reservation,
                  self.paid_for,
                  self.shipped,
                  self.ship_to.address,
                  self.creation_date,
                  self.order_status]
        return to_csv_from_array(values)

    @classmethod
    def create_from_csv(cls, csv):
        filtered_values = to_array_from_csv(csv)
        order = Order(order_number=filtered_values[0],
                      reserved_for=Customer.objects.get(contact_id=filtered_values[1]),
                      paid_for=filtered_values[2],
                      shipped=filtered_values[3],
                      ship_to=ShippingAddress.objects.get(address=filtered_values[4]),
                      creation_date=filtered_values[5],
                      order_status=filtered_values[6])
        order.save()
        return order

    def get_weight(self):
        order_weight = 0.0
        for order_box in self.orderbox_set.all():
            order_weight = float(order_weight) + float(order_box.box.weight)
        return ("%.1f" % order_weight)

    def get_cost(self):
        if self.price is not None:
            return ('%.2f' % self.price)

        order_cost = 0.0
        for order_box in self.orderbox_set.all():
            order_cost = float(order_cost) + float(order_box.cost)
        return ("%.2f" % order_cost)

    def get_creation_date_display(self):
        creation_date = str(self.creation_date).split(' ')[0]
        creation_array = creation_date.split('-')
        return creation_array[1] + '/' + creation_array[2] + '/' + creation_array[0]

class OrderBox(models.Model):
    order_for = models.ForeignKey(Order)
    box = models.ForeignKey(Box)
    cost = models.FloatField(default=0.0)

    def __unicode__(self):
        return str(self.box) + " in " + str(self.order_for)

    def to_csv(self):
        values = [self.order_for.order_number,
                  self.box.box_id,
                  self.cost]
        return to_csv_from_array(values)

    @classmethod
    def create_from_csv(cls, csv):
        filtered_values = to_array_from_csv(csv)
        order_box = OrderBox(order_for=Order.objects.get(order_number=filtered_values[0]),
                             box=Box.objects.get(box_id=filtered_values[1]),
                             cost=filtered_values[2])
        order_box.save()
        return order_box

class LockedBoxNotification(models.Model):
    removed_from_order = models.ForeignKey(Order)
    box = models.ForeignKey(Box)

MediVol/orders/views.py
from django.shortcuts import render, render_to_response
from django.contrib.auth.decorators import login_required, user_passes_test
from administration.UserTests import UserTests

from catalog.models import Category
from orders.models import Order, OrderBox, LockedBoxNotification
from inventory.models import Box

@login_required(login_url='/login/')
@user_passes_test(UserTests.user_is_admin, login_url='/administration/forbidden')
def orders_home(request):
    choices = Order._meta.get_field('order_status').choices
    orders = Order.objects.exclude(order_status='F').exclude(order_status='S')
    context = { 'orders': orders, 'statuses': choices}

    return render(request, 'orders/orders.html', context)

@login_required(login_url='/login/')
@user_passes_test(UserTests.user_is_admin, login_url='/administration/forbidden')
#Display the create page of ordering
def create_order(request, order_id=0, step_num=1, box_to_add='0'):
    step_num = int(step_num)
    categories = Category.objects.all()
    categoryStrings = []
    order = False
    num_addresses = 0
    num_boxes = 0
    total_price = 0.00
    custom_price = 0.00

    if order_id != 0:
        try:
            order = Order.objects.get(id=order_id)
            num_addresses = len(order.reserved_for.shippingaddress_set.all())
            num_boxes = len(order.orderbox_set.all())

            for order_box in order.orderbox_set.all():
                total_price = total_price + order_box.cost

            custom_price = order.price
        except Order.DoesNotExist:
            order_id = 0

    for category in categories:
        categoryStrings.append(category.name)

    if total_price is None:
        total_price = 0.00

    if custom_price is None:
        custom_price = 0.00

    box = None

    if box_to_add != '0':
        box = Box.get_box(box_to_add)

    context = {
        'categories': sorted(categoryStrings),
        'order_id': order_id,
        'order': order,
        'num_addresses': num_addresses,
        'num_boxes': num_boxes,
        'total_price': '%.2f' % total_price,
        'custom_price': '%.2f' % custom_price,
        'step_num': step_num,
        'box_to_add': box
    }

    return render(request, 'orders/create_order.html', context)

@login_required(login_url='/login/')
@user_passes_test(UserTests.user_is_admin, login_url='/administration/forbidden')
# Display order review page
def order_review(request, orderid):
    try:
        #Try and get order to review, if the order id exists return
        order = Order.objects.get(id=orderid)
    except:
        try:
            order = Order.objects.get(order_number=orderid)
        except Order.DoesNotExist:
            # If order id does not exist in database redirect to order not found page
            return render_to_response('orders/order_not_found.html')

    boxes = []
    box_orderbox_pair = []
    locked_boxes = LockedBoxNotification.objects.filter(removed_from_order=order)

    if locked_boxes.count() == 0:
        locked_boxes = None
    else:
        locked_box_strings = []

        for locked_box in locked_boxes:
            locked_box_strings.append(locked_box.box.get_url())

        locked_boxes = ', '.join(locked_box_strings)

    response = {
        'order_boxes': OrderBox.objects.filter(order_for=order),
        'order': order,
        'order_statuses': Order.ORDER_STATUS,
        'locked_boxes': locked_boxes
    }

    return render(request, 'orders/review_order.html', response)

MediVol/orders/templates/orders/order_not_found.html
{% extends 'base.html' %}

{% block title %}
    <title>InterVol | Order Not Found</title>
{% endblock %}

{% block body %}
    <h2>Order Not Found</h2>
{% endblock %}

MediVol/orders/templates/orders/orders.html
{% extends 'base.html' %}

{% block title %}
    <title>InterVol | Orders</title>
{% endblock %}

{% block styles %}
    <link rel='stylesheet' href='{{ STATIC_URL }}orders/css/orders.css' />
{% endblock %}

{% block body %}
    <h2>Orders</h2>

    <a id='createOrder' href='/orders/create'><button class='button'>Create Order</button></a>
<div></div>
    <div id='tableWrapper'>
        <table id='orders_found'>
            <tr id='table_header'>
                <td id='idHeader'>Order ID</td>
                <td id='statusHeader'>Status</td>
                <td id='forHeader'>Reserved For</td>
                <td id='dateHeader'>Created On</td>
                <td id='priceHeader'>Price</td>
                <td id='weightHeader'>Weight</td>
            </tr>
                <tbody id="orders_body">
                    {% for order in orders %}
                    <tr id='order{{ order.id }}'>
                        <td>
                            <a href="/orders/review/{{ order.id }}">{{ order.order_number }}</a>
                        </td>
                        <td>{{ order.get_order_status_display }}</td>
                        <td>{{ order.reserved_for.contact_name }}</td>
                        <td>{{ order.get_creation_date_display }}</td>
                        <td>${{ order.get_cost|floatformat:'2' }}</td>
                        <td>{{ order.get_weight|floatformat:'1' }} lbs</td>
                    </tr>
                    {% endfor %}
                </tbody>
        </table>
    </div>

    <label id='statusSelectLabel' for='statusSelect'>Show</label>
    <select id="statusSelect">
        <option value="All Open" selected="selected">All Open</option>
        {% for status in statuses %}
            <option value="{{ status.0 }}">{{ status.1 }}</option>
        {% endfor %}
        <option value="All Orders">All Orders</option>
    </select>
{% endblock %}

{% block javascript %}
    <script type='text/javascript' src='{{ STATIC_URL }}orders/js/orders.js'></script>
{% endblock %}

MediVol/orders/templates/orders/review_order.html
{% extends 'base.html' %}

{% block title %}
    <title>InterVol | {{ order.order_number }}</title>
{% endblock %}

{% block styles %}
    <link rel='stylesheet' href='{{ STATIC_URL }}orders/css/style.css' />
    <link rel='stylesheet' href='{{ STATIC_URL }}orders/css/review_style.css' />
{% endblock %}

{% block body %}
    <h2>{{ order.order_number }}</h2>

    {% if locked_boxes != None %}
        <div id='boxNotification' class='noItemSelected'>
            <div id='dontShowAgain'>Don't show again</div>
            The following boxes are no longer available to this order:

            {{ locked_boxes|safe }}
        </div>
    {% endif %}

    <div id='customerInfoWrapper'>
        <p class='contactName'>{{ order.reserved_for.contact_name }}</p>
        <p class='businessName'>{{ order.reserved_for.business_name }}</p>

        <div class='addressWrapper'>
            <p class='addressHeader'>Business Address</p>
            <p class='businessAddress'>{{ order.reserved_for.business_address|linebreaksbr }}</p>
        </div>

        {% if order.ship_to != None %}
            <div class='addressWrapper'>
                <p class='addressHeader'>Shipping Address</p>
                <p class='shippingAddress'>{{ order.ship_to.address|linebreaksbr }}</p>
            </div>
        {% endif %}

        <div class='addressWrapper'>
            <p class='addressHeader'>Status</p>
            <p class='shippingAddress'>
                <select id='orderStatus'>
                    {% for order_status in order_statuses %}
                        {% if order_status.0 == order.order_status %}
                            <option value='{{ order_status.0 }}' selected='selected'>{{ order_status.1 }}</option>
                        {% else %}
                            <option value='{{ order_status.0 }}'>{{ order_status.1 }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </p>
        </div>

        <div class='clear'></div>
    </div>

    <div id='tableWrapper'>
        <table id='boxes_added'>
            <tr id='table_header'>
                <td>Box ID</td>
                <td>Size</td>
                <td>Weight</td>
                <td>Price</td>
            </tr>

            {% for order_box in order_boxes %}
                <tr id='box_info'>
                    <td>
                        <a href='/inventory/view_box_info/{{ order_box.box.get_id }}' target='_blank'>
                            {{ order_box.box.get_id }}
                        </a>
                    </td>
                    <td>{{ order_box.box.get_box_size_display }}</td>
                    <td>{{ order_box.box.weight|floatformat:'1' }} lbs</td>
                    <td>
                        ${{ order_box.cost|floatformat:'2' }}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>

    <div id='orderInfoWrapper'>
        <div id='orderInfoLeft'>
            <a href='/orders/create/{{ order.id }}'>
                <button class='button editOrderButton'>Edit Order</button></a>

            <button class='button deleteOrderButton'>Delete Order</button>
            <button id="downloadOrder" class='button downloadButton'>Download Packing List</button>
        </div>

        <div id='orderInfoRight'>
            <h3>Total Weight: {{ order.get_weight|floatformat:'1' }} lbs</h3>
            <h3>Order Price: ${{ order.get_cost|floatformat:'2' }}</h3>
        </div>

        <div class='clear'></div>
    </div>
{% endblock %}

{% block javascript %}
    <script type='text/javascript'>
        var orderId = {{ order.id }};
        var orderName = '{{ order.order_number }}';
    </script>
    <script type='text/javascript' src='{{ STATIC_URL }}orders/js/review.js'></script>
{% endblock %}